export type IntegritySeverity =
  | "error"
  | "warning"
  | "info";

export type IntegrityArea =
  | "command"
  | "execution_plan"
  | "execute_handler"
  | "scenario_id"
  | "scenario_registry"
  | "preview"
  | "scenario_facts"
  | "completion"
  | "alias"
  | "reachability"
  | "procedure"
  | "scenario_completeness"
  | "golden_path"
  | "wrong_order"
  | "state_mutation"
  | "repeat_behavior"
  | "decision_coverage"
  | "restart"
  | "scenario_isolation"
  | "mode"
  | "playlist"
  | "history"
  | "score";

export type IntegrityFindingCode =
  | "COMMAND_PLAN_MISSING"
  | "EXECUTION_PLAN_HANDLER_MISSING"

  | "SCENARIO_ID_DUPLICATE"
  | "SCENARIO_ID_MISSING_FROM_REGISTRY"
  | "REGISTRY_SCENARIO_ID_INVALID"

  | "SCENARIO_LABEL_MISSING"
  | "SCENARIO_PROMPT_MISSING"
  | "SCENARIO_PROCEDURE_MISSING"
  | "SCENARIO_DEFAULTS_MISSING"
  | "SCENARIO_CATEGORY_MISSING"
  | "SCENARIO_TYPE_MISSING"

  | "SCENARIO_COMPLETION_METADATA_MISSING"
  | "COMPLETION_FACT_MISSING"
  | "COMPLETION_COMMAND_MISSING"

  | "SCENARIO_PREVIEW_METADATA_MISSING"
  | "SCENARIO_PREVIEW_DESCRIPTION_MISSING"
  | "SCENARIO_PREVIEW_SKILL_FOCUS_MISSING"
  | "SCENARIO_PREVIEW_CONTEXT_MISSING"
  | "SCENARIO_PREVIEW_SUCCESS_OUTCOME_MISSING"
  | "SCENARIO_PREVIEW_SELECT_COMMAND_MISSING"
  | "PREVIEW_SCENARIO_MISSING"

  | "SCENARIO_PROOF_LINES_MISSING"
  | "SCENARIO_SUCCESS_LINES_MISSING"
  | "SCENARIO_FACTS_MISSING"
  | "SCENARIO_FACT_KIND_MISMATCH"

  | "SCENARIO_FINAL_STEP_MISMATCH"
  | "SCENARIO_PROCEDURE_PREVIEW_MISSING"
  | "SCENARIO_ADJACENT_PROCEDURE_DUPLICATE"
  | "SCENARIO_FINAL_VERIFICATION_MISSING"
  | "SCENARIO_COMPLETION_FACT_NOT_FALSE"
  | "SCENARIO_PROCEDURE_TOO_SHORT"

  | "GOLDEN_PATH_SELECTION_DENIED"
  | "GOLDEN_PATH_START_DENIED"
  | "GOLDEN_PATH_STEP_DENIED"
  | "GOLDEN_PATH_EARLY_PASS"
  | "GOLDEN_PATH_COMPLETION_MISSING"
  | "WRONG_ORDER_COMMAND_ALLOWED"
  | "WRONG_ORDER_STATE_MUTATED"
  | "WRONG_ORDER_EARLY_PASS"

  | "STATE_MUTATION_UNDECLARED_FACT_CHANGED"
  | "STATE_MUTATION_EXPECTED_FACT_UNCHANGED"
  | "STATE_MUTATION_UNEXPECTED_RESULT_CHANGE"
  | "STATE_MUTATION_CONTRACT_MISSING"

  | "REPEAT_COMMAND_ALLOWED"
  | "REPEAT_SCENARIO_STATE_MUTATED"
  | "REPEAT_RESULT_MUTATED"
  | "REPEAT_CAUSED_COMPLETION"

  | "RESTART_DENIED"
  | "RESTART_EXECUTION_STATE_INVALID"
  | "RESTART_SCENARIO_CHANGED"
  | "RESTART_ATTEMPT_NOT_REPLACED"
  | "RESTART_RESULT_NOT_CLEARED"
  | "RESTART_SCENARIO_FACTS_NOT_RESET"
  | "RESTART_PROGRESS_PRESERVED"
  | "RESTART_HELP_STATE_NOT_RESET"

  | "SCENARIO_ISOLATION_SELECTION_DENIED"
  | "SCENARIO_ISOLATION_SELECTION_STATE_LEAK"
  | "SCENARIO_ISOLATION_START_DENIED"
  | "SCENARIO_ISOLATION_WRONG_SCENARIO"
  | "SCENARIO_ISOLATION_FACTS_LEAK"
  | "SCENARIO_ISOLATION_RESULT_LEAK"
  | "SCENARIO_ISOLATION_ATTEMPT_INVALID"
  | "SCENARIO_ISOLATION_HELP_STATE_LEAK"
  | "SCENARIO_ISOLATION_COMPLETION_TRANSITION_DENIED"

  | "MODE_PRACTICE_HELP_DENIED"
  | "MODE_PRACTICE_RESTART_DENIED"
  | "MODE_PRACTICE_QUIT_DENIED"
  | "MODE_ASSESSMENT_HELP_ALLOWED"
  | "MODE_ASSESSMENT_RESTART_ALLOWED"
  | "MODE_ASSESSMENT_QUIT_DENIED"

  | "PLAYLIST_ADVANCE_NOT_PRODUCED"
  | "PLAYLIST_INDEX_ADVANCE_INVALID"
  | "PLAYLIST_NEXT_SCENARIO_INVALID"
  | "PLAYLIST_FINAL_SCENARIO_NOT_COMPLETED"
  | "PLAYLIST_COMPLETED_STATUS_INVALID"
  | "PLAYLIST_COMPLETION_END_TIME_MISSING"
  | "PLAYLIST_FINISHED_RUN_ADVANCED"
  | "PLAYLIST_ATTEMPT_ATTACHMENT_INVALID"
  | "PLAYLIST_ATTEMPT_DUPLICATED"
  | "PLAYLIST_ATTEMPT_MUTATED_SEQUENCE"
  | "PLAYLIST_ABANDON_STATUS_INVALID"
  | "PLAYLIST_ABANDON_END_TIME_MISSING"
  | "PLAYLIST_ABANDON_ATTEMPT_MISSING"
  | "PLAYLIST_FINISHED_RUN_ABANDONED"

  | "HISTORY_COMPLETED_RECORD_MISSING"
  | "HISTORY_COMPLETED_RESULT_INVALID"
  | "HISTORY_COMPLETED_METADATA_INVALID"
  | "HISTORY_QUIT_RECORD_INVALID"
  | "HISTORY_RESTART_RECORD_INVALID"
  | "HISTORY_ABANDONED_MISTAKES_INVALID"
  | "HISTORY_RECORD_CREATED_WITHOUT_ATTEMPT"
  | "HISTORY_RECORD_CREATED_WITHOUT_SCENARIO"
  | "HISTORY_DUPLICATE_ATTEMPT_ALLOWED"

  | "SCORE_PERFECT_RUN_INVALID"
  | "SCORE_SINGLE_DENY_INVALID"
  | "SCORE_ALLOW_COUNTED_AS_MISTAKE"
  | "SCORE_FLOOR_INVALID"
  | "SCORE_COMPLETION_NOT_PRESERVED"

  | "PROCEDURE_DECISION_DEFINITION_MISSING"
  | "PROCEDURE_DECISION_RULE_MISSING"
  

  | "COMMAND_UNREACHABLE"
  | "COMMAND_ALIAS_DUPLICATE"
  | "PROCEDURE_ORPHANED";

export type IntegrityFinding = {
  severity: IntegritySeverity;
  area: IntegrityArea;
  code: IntegrityFindingCode;

  message: string;
  source: string;

  scenarioId?: string;
  command?: string;
  executionPlan?: string;
  alias?: string;
  fact?: string;
};

export type IntegrityAreaSummary = {
  area: IntegrityArea;
  checkedCount: number;
  errorCount: number;
  warningCount: number;
  passed: boolean;
};

export type ArchitectureHealthReport = {
  reportName: "Architecture Integrity";

  checkedCount: number;
  errorCount: number;
  warningCount: number;
  infoCount: number;

  passed: boolean;

  summaries: readonly IntegrityAreaSummary[];
  findings: readonly IntegrityFinding[];
};

export type ArchitectureIntegrityCheck = {
  name: string;
  area: IntegrityArea;

  run: () => readonly IntegrityFinding[];
};